### PR TITLE
Convert barcode.cornerPoints to something JS-usable on iOS

### PR DESCRIPTION
**Pull request by chiubaka**
Converts the `cornerPoints` prop on retrieved Barcode objects on iOS so that `cornerPoints` is usable in JS.

### CODE REVIEW

**Comment by chiubaka** [comment]
I haven't quite had a chance to test this yet--will do so later tonight my time when my girlfriend comes back with her iPhone :P.

**Comment by chiubaka** [comment]
Should resolve #17.

**Comment by chiubaka** [comment]
Updated! This should work as provided. Of note: I am having trouble getting the provided corner points to match-up with the detected QR code in the preview as an overlay.

**Comment by chiubaka** [comment]
I was able to get the overlay in the preview working. The key is to realize that the preview dimensions are _not_ the same as the frame dimensions as processed by this frame processor. The preview is a resized version of what the camera actually sees, resized using an "aspect fill" method meaning that the aspect ratio of the original is maintained, the image is scaled down until it would fill the entirety of the preview space, and then any excess is cropped after the image is centered.

In order to translate the provided points into the preview's coordinate space, you need to find the relative scale of the image to the preview, then figure out how much cropping was done in either the vertical or horizontal dimension, and transform the coordinates appropriately.

**Comment by rodgomesc** [comment]
> method meaning that the aspect ratio of the original is maintained, the image is scaled down until it would fill the entirety of the preview space, and then any excess is cropped after the image is centered.

hmmm, that's really interestting, you have some example code about how to do that?

**Comment by chiubaka** [comment]
You can likely glean it from this:
```
import { useKeepAwake } from "expo-keep-awake";
import barcodes from "jsbarcode/src/barcodes";
import { Box, Center, Text } from "native-base";
import React, { ComponentType, useMemo, useState } from "react";
import { LayoutChangeEvent, Platform, StyleSheet } from "react-native";
import { Rect, Svg } from "react-native-svg";

import { PrintedEReceipt, PrintedEReceiptInput } from "../../entities";
import { StringUtils } from "../../utils";
import {
  Bounds,
  Dimensions,
  Point,
  QrCode,
  QrCodeScannerProps,
  RnCameraQrCodeScanner,
  VisionCameraQrCodeScanner,
} from "./QrCodeScanner";

interface ReceiptScannerProps
  extends Omit<
    QrCodeScannerProps,
    "onQrCodesScanned" | "onFrameDimensionsChange"
  > {
  onReceiptScanned: (receipt: PrintedEReceiptInput) => Promise<void>;
}

export const ReceiptScanner = (props: ReceiptScannerProps) => {
  const { onReceiptScanned, ...scannerProps } = props;

  useKeepAwake();

  const [qrCodes, setQrCodes] = useState<QrCode[]>([]);
  const [previewSize, setPreviewSize] = useState<Dimensions>();
  const [frameSize, setFrameSize] = useState<Dimensions>();

  const bestScalingFactor = useMemo<number | null>(() => {
    if (previewSize == null || frameSize == null) {
      return null;
    }

    const horizontalScalingFactor = previewSize.width / frameSize.width;
    const verticalScalingFactor = previewSize.height / frameSize.height;

    return Math.max(horizontalScalingFactor, verticalScalingFactor);
  }, [frameSize, previewSize]);

  const computeMargin = (
    previewDim: number,
    frameDim: number,
    scalingFactor: number,
  ) => {
    const scaledFrameDim = frameDim * scalingFactor;
    const overflow = scaledFrameDim - previewDim;
    return overflow / 2;
  };

  const horizontalMargin = useMemo<number | null>(
    () => {
      if (
        previewSize == null ||
        frameSize == null ||
        bestScalingFactor == null
      ) {
        return null;
      }

      return computeMargin(
        previewSize.width,
        frameSize.width,
        bestScalingFactor,
      );
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [bestScalingFactor],
  );

  const verticalMargin = useMemo<number | null>(
    () => {
      if (
        previewSize == null ||
        frameSize == null ||
        bestScalingFactor == null
      ) {
        return null;
      }

      return computeMargin(
        previewSize.height,
        frameSize.height,
        bestScalingFactor,
      );
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [bestScalingFactor],
  );

  const computeBounds = (cornerPoints: Point[]): Bounds => {
    let maxX = Number.NEGATIVE_INFINITY;
    let minX = Number.POSITIVE_INFINITY;

    let maxY = Number.NEGATIVE_INFINITY;
    let minY = Number.POSITIVE_INFINITY;

    cornerPoints.forEach((point) => {
      const { x, y } = point;
      if (x > maxX) {
        maxX = x;
      }

      if (x < minX) {
        minX = x;
      }

      if (y > maxY) {
        maxY = y;
      }

      if (y < minY) {
        minY = y;
      }
    });

    return {
      topLeft: {
        x: minX,
        y: minY,
      },
      bottomRight: {
        x: maxX,
        y: maxY,
      },
    };
  };

  const isValidReceipt = (
    receipt: PrintedEReceiptInput | null,
  ): receipt is PrintedEReceiptInput => {
    return (
      receipt != null && receipt.number != null && receipt.issuedAt != null
    );
  };

  const handleLayoutChange = (event: LayoutChangeEvent) => {
    const { layout } = event.nativeEvent;
    console.log(`Preview: ${layout.width}x${layout.height}`);
    setPreviewSize(event.nativeEvent.layout);
  };

  const handleFrameDimensionsChange = (dimensions?: Dimensions) => {
    setFrameSize(dimensions);
  };

  const handleQrCodesScanned = async (qrCodes: QrCode[]) => {
    setQrCodes(qrCodes);

    const promises = qrCodes.map(handleQrCodeScanned);
    await Promise.all(promises);
  };

  const handleQrCodeScanned = (qrCode: QrCode): Promise<void> => {
    const parsedReceipt = PrintedEReceipt.parseQrCodeData(qrCode.value);

    if (!isValidReceipt(parsedReceipt)) {
      return Promise.resolve();
    }

    return onReceiptScanned(parsedReceipt);
  };

  const renderHeader = () => {
    <Center style={styles.overlay}>{renderDetectionLabel()}</Center>;
  };

  const renderDetectionLabel = () => {
    const quantity = qrCodes.length === 0 ? "No" : barcodes.length;
    const noun = StringUtils.pluralize(qrCodes.length, "code", "codes");

    return (
      <Text color="white" fontSize="sm" fontWeight="bold">
        {quantity} QR {noun} detected
      </Text>
    );
  };

  const renderBoundingBoxes = () => {
    const boundingBoxes = qrCodes.map(renderBoundingBox);
    return <Svg style={styles.overlay}>{boundingBoxes}</Svg>;
  };

  const renderBoundingBox = (qrCode: QrCode) => {
    const { cornerPoints, value } = qrCode;

    // We'll need the dimensions in order to compute a scaling factor for proper bounding box rendering.
    // If this values aren't ready yet, skip rendering bounding boxes until they are.
    if (
      cornerPoints == null ||
      cornerPoints.length !== 4 ||
      bestScalingFactor == null ||
      horizontalMargin == null ||
      verticalMargin == null
    ) {
      return null;
    }

    const { topLeft, bottomRight } = computeBounds(cornerPoints);

    const scale = (value: number) => {
      return value * bestScalingFactor;
    };

    const horizontalTransform = (value: number) => {
      return scale(value) - horizontalMargin;
    };

    const verticalTransform = (value: number) => {
      return scale(value) - verticalMargin;
    };

    const x = horizontalTransform(topLeft.x);
    const y = verticalTransform(topLeft.y);

    const width = scale(bottomRight.x - topLeft.x);
    const height = scale(bottomRight.y - topLeft.y);

    const sideLength = Math.max(width, height);

    console.log(`bestScalingFactor: ${bestScalingFactor}`);
    console.log(`horizontalMargin: ${horizontalMargin}`);
    console.log(`verticalMargin: ${verticalMargin}`);

    console.log(`Rendering rectangle: (${x}, ${y}) ${width}x${height}`);

    // TODO: Corner points are not guaranteed to represent a rectangle due
    // to perspective skew. Should we render a polygon instead?
    return (
      <>
        <Rect
          key={value}
          x={x}
          y={y}
          width={sideLength}
          height={sideLength}
          fill="rgba(0, 0, 255, 0.25)"
        />
      </>
    );
  };

  const QrCodeScanner: ComponentType<QrCodeScannerProps> =
    Platform.OS === "ios" ? VisionCameraQrCodeScanner : RnCameraQrCodeScanner;

  return (
    <Box style={StyleSheet.absoluteFill} onLayout={handleLayoutChange}>
      {renderBoundingBoxes()}
      <QrCodeScanner
        onFrameDimensionsChange={handleFrameDimensionsChange}
        onQrCodesScanned={handleQrCodesScanned}
        {...scannerProps}
      />
      {renderHeader()}
    </Box>
  );
};

const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1000,
  },
});
```

**Comment by rodgomesc** [comment]
that's great thanks \o/

**Comment by rodgomesc** [comment]
Closes #17

**Pull request merged**
